# Generated by Django 4.2 on 2024-09-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('item', models.CharField(max_length=100, verbose_name='支出項目')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('payment_method', models.CharField(choices=[('Cash', '現金'), ('Credit Card', '信用卡'), ('Bank Transfer', '銀行轉帳')], max_length=20, verbose_name='支付方式')),
                ('receipt', models.ImageField(upload_to='receipts/', verbose_name='收據或發票')),
                ('category', models.CharField(choices=[('Fixed', '固定支出'), ('Variable', '變動支出')], max_length=20, verbose_name='支出分類')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
            ],
        ),
    ]
