# Generated by Django 4.2 on 2024-09-04 02:15

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('fixed', '固定支出'), ('variable', '變動支出')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', '現金'), ('credit_card', '信用卡'), ('bank_transfer', '銀行轉帳')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=management.models.upload_to),
        ),
        migrations.AlterField(
            model_name='expense',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
