# Generated by Django 4.2 on 2024-09-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='回饋點數'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to='customer.customer', verbose_name='介紹人'),
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='獲得回饋點數'),
        ),
    ]
